### ISSUE TITLE
how do i do this whole thing?

### ISSUE THREAD

**Issue by 2trueAaron** [acquitelol/azalea#26]
i need help really badly because i dont know how to run this script. i am on mac and using chrome incognito, what do i do?

**Comment by acquitelol** [comment]
You'll need to:

- Download the .zip file from [releases](https://github.com/acquitelol/azalea/releases/latest)
- Unzip it (by double clicking on the file)
- Click on the hamburger/"..." menu in Chrome (should be at the top right), look for the Extensions button in that pop up and open the Extensions tab
- Enable the "Developer Mode" toggle in that page, then click on "Load Unpacked" and select the folder that you unzipped earlier.

Now if you refresh Sparx, Azalea should load. You can check this by going to the Hamburger menu at the top right if Sparx and clicking on "Settings".

Note: I'm not sure if extensions can be loaded in incognito, but more likely than not they can.

**Comment by 2trueAaron** [comment]
<img width="166" alt="Screenshot 2024-05-06 at 18 18 07" src="https://github.com/acquitelol/azalea/assets/169072472/cf783396-e929-4d52-a81e-70d2aa13446f">
it says none next to my xp so how do i make this script work? like the calculator thingy u said but i dont see it if i try and do my work, what do i do?

**Comment by 2trueAaron** [comment]
<img width="1511" alt="Screenshot 2024-05-06 at 18 21 22" src="https://github.com/acquitelol/azalea/assets/169072472/36c5b0c7-da89-4f73-979e-77870ec0c322">
and it says loading azalea but nothing appears.

**Comment by acquitelol** [comment]
The "None" shows your currently applied theme. You can change it from the settings page I mentioned above. There's no calculator built-in, you can just use like Mathway or something.

For the actual features of Azalea please look at the readme.

**Comment by acquitelol** [comment]
No reply, assuming issue was resolved.
